<div id="dWelcome">
<div id="homeSlideShow">
    <div class="image pics">
        <div class="item">
            <a href="?p=technology&u=videogame">
                <img src="technology/videogame/mosaico.jpg" />
                <span class="description">From tennis on the oscilloscope to 16-bit consoles: article shows the first 40 years of video game history</span>
            </a>
        </div> 		  
        <div class="item">
            <a href="?p=curriculum">
                <img src="curriculum/sample.png" />
                <span class="description">See our curriculum</span>
            </a>
        </div> 		  
        <div class="item">
            <a href="?p=abstract&u=forrestgump">
                <img src="abstract/forrestgump/home.jpg" />
                <span class="description">Forrest Gump is a 1986 novel by Winston Groom. The title character experiences adventures ranging from shrimp boating and ping pong championships to  ...
</span>
            </a>
        </div> 		  
        <div class="item">
            <a href="?p=letter">
                <img src="letter/sample.jpg" />
                <span class="description">Letter of presentation: Read about what we can do for your company</span>
            </a>
        </div> 

    </div>
    <div id="prevSS"><a href="javascript:void(0);">&laquo; Prev</a></div><div id="nextSS"><a href="javascript:void(0);">Next &raquo;</a></div>
</div>


<div class="welcome">

    <div class="nota principal">
							       
        <p class="minidesc">The first 40 years of video games</p>
        <h3>
            <a href="?p=technology&u=videogame">				 
                From tennis on the oscilloscope to 16-bit consoles</a>
        </h3>

        <p id="artVideogame">
            Article shows the first 40 years of video game history
        </p>
    </div>
    <div class="nota">
        <p class="minidesc">Essay</p>
        <h3><a href="?p=abstract&u=ipv6">IPv4 addresses are over. Now what?</a></h3>
        <p>
            In the current version IPv4 protocol, is already quite old and has enough problems. The biggest problem is the address scalability limit. Now what?
        </p>
    </div>
     <div class="nota">
        <p class="minidesc">Essay</p>
        <h3><a href="?p=abstract&u=forrestgump">More than a well told story</a></h3>
        <p>Forrest Gump is a 1986 novel by Winston Groom. The title character experiences adventures ranging from shrimp boating and ping pong championships to  ...
        </p>
    </div>
    <div class="nota">
        <p class="minidesc">Documents</p>
        <h3><a href="?p=letter">Letter of presentation</a></h3>
        <p>
            Read about what we can do for your company
        </p>
    </div>	
    <div class="nota">
        <p class="minidesc">Documents</p>	
        <h3><a href="?p=curriculum">Curriculum Vitae</a></h3>
        <p>
            See our curriculum
        </p>
    </div>
</div>
</div>