
<h2>Fundamentos da Interface Humano-Computador 
    <br />e <br />
    Inglês Instrumental</h2>
<h2>Projeto – Criação de um Blog </h2>
<strong>Objetivo:</strong>  Criar um blog para aplicação dos conceitos de Interface 
Homem-Computador. Redigir 4 gêneros textuais em língua inglesa.
</p>
<p>
    <strong>Conteúdo:</strong>  CV,  letter of  presentation,  abstract,  essay about 
    technology 
</p>
<p>
    <strong>Grupo:</strong> 3 alunos 
</p>
<p>
    Avaliação: Serão avaliados a aplicação de conceitos de Interface 
    Homem-Computador na criação do blog e os aspectos linguísticos dos 
    textos em inglês.
</p>
<p>
    <strong>Parte 1</strong>  Entrega: 06/10/2011
</p>

<ol>
    <li>Faça um plano do blog a ser desenvolvido</li> 
    <li>Identifique as necessidades e estabeleça os requisitos do blog </li>
    <li>Desenvolva designs alternativos que preencham esses requisitos </li>
    <li>Construa designs alternativos dos designs e apresente suas 
        avaliações </li>
    <li>Quais critérios de usabilidade irão ser utilizados para determinar a 
        qualidade do seu blog.</li>
</ol> 
<p>
    <strong>Observação:</strong> Não se esqueça de responder todas as questões 
    práticas para desenvolvimento de design de interação. 
</p>
<p>
    <strong>Parte 2</strong> Entrega dos textos em inglês: 26/10/2011
</p>

<ol>
    <li>Postar os textos</li>
    <li>Disponibilizar os endereços à professora de inglês</li>
    <li>Reajustar, de acordo com as correções da professora</li>
</ol>

<p>
    <strong>Parte 3</strong> Entrega: 10/11/2011
</p>
<ol>

    <li>Apresente como foi efetuada cada fase do projeto básico de 
        iteração.</li>
    <li>Narre como foi efetuado o processo do projeto.</li>
    <li>Como foi tratado o usuário? Qual foco foi dado para este usuário?</li>
    <li>Como se caracteriza a navegação do blog em desenvolvimento.</li>
    <li>Qual a aparência utilizada no blog? Cite todas, mostrando-as.</li>
    <li>Quais os princípios e qualidades que foram utilizadas para apoiar a 
        usabilidade?</li>
    <li>Foi implementada alguma ajuda ao usuário para utilização deste 
        blog? </li>
    <li>Como foram escolhidas as cores? Justifique porque as cores 
        escolhidas foram utilizadas.</li>
    <li>Quais modelos cognitivos foram utilizados?</li></ol>
<p>
    <strong>Parte 4</strong> Apresentação: 16 e 23/11/2011
</p>
<p>
    O Blog desenvolvido deve ser apresentado para a sala mostrando as 
    características descritas nas partes 1 e  3 e comentando os textos 
    desenvolvidos na parte 2.
</p>

</pre>