
<h2>Essay</h2>

  <div id="listAbstract">
     
     
     <div class="abstract">
     
          <img class="mini" src="<?php 
          include 'ipv6/abstract.php'; 
          echo $abstract->picture; 
          ?>" >           
          <div class="contents">
	          <strong><a href="?p=abstract&u=ipv6"><?php echo $abstract->name; ?></a></strong>
	          <div class="details">
	             <?php echo $abstract->description ;  ?>
	          </div>
          </div>
     </div>      
     <div class="abstract">
         
          <img class="mini" src="/boblog/abstract/forrestgump/mini.jpg" />
          <div class="contents">
	          <strong><a href="?p=abstract&u=forrestgump">More than a well told story</a></strong>
	          <div class="details">'Winston Groom, 67, is the writer of the acclaimed novel about the Vietnam War, <em>"Better times than these"</em>. He has published eight books and was nominated for the Pulitzer Prize. Forest Gump - The Storyteller, (adapted for film in 1994) is his fifth book. Launched in 1986, ...[<a href="?p=abstract&u=forrestgump">read more</a>]
	          </div>
          </div>
         
          
          
          </div>
     </div>

     

     
        

