<h2>Curriculum Vitae</h2>

<p>This is the page where you can view the curriculum vitae
of the creators of this site. Click one to view.</p>

<div id="listCurriculum" data-role="listview">
     <div class="pessoa bruna"  >
          <img class="mini" src="<?php include 'bruna/c.php'; echo $cv->picture; ?>" >           
          <div class="contents">
          <strong><a href="?u=bruna&p=curriculum">Bruna Liberali</a></strong>
          <div class="details">Skills in design, Adobe Photoshop, ... [<a href="?u=bruna&p=curriculum">read more...</a>]
          
          </div>
          
          </div>
     </div>
     <div class="pessoa zanelli">
          <img class="mini" src="<?php include 'zanelli/c.php'; echo $cv->picture; ?>" >    
          <div class="contents">
          
          <strong><a href="?u=zanelli&p=curriculum">Wellington Zanelli</a></strong>
          <div class="details">Skills in SQL Server, JavaScript, CSS, ASP 3.0,...  [<a href="?u=zanelli&p=curriculum">read more...</a>]
          
          </div>
          </div>
          
     </div>
     <div class="pessoa tiago">
          <img class="mini" src="<?php include 'tiago/c.php'; echo $cv->picture; ?>" >    
          <div class="contents">
          <strong><a href="?u=tiago&p=curriculum">Tiago Donizetti  </a></strong>
          <div class="details">Skills in programming (PHP, Visual Basic, C, Java)... [<a href="?u=tiago&p=curriculum">read more...</a>]
          </div>
          </div>
     </div>     
</div>

