<div id="cv">
    <h2>EmptyUser - Curriculum Vitae</h2>
    <div id="cvPicture">
        <img src="curriculum/empty.gif" alt="name" />
    </div>
    <div id="cvDetails">
        <dt>Address:</dt><dd>??? ???????????? </dd>
        <dt>Telephone:</dt><dd>0000-0000</dd>
        <dt>E-mail: </dt><dd><a href="mailto:mail@mail.com">mail@mail.com</a></dd>
        <dt>Nationality: </dt><dd>Brazilian</dd>
        <dt>Age: </dt><dd>00</dd>
    </div>
    <h3>Education and training</h3>
    <div id="cvEducationTraining">
        <div class="curse">
            <dt>2010</dt>
            <dd>
                <span class="name">Internet Systems Technology Course (college) </span> - 
                <span class="local">São Paulo Federal Institute of Education, Science and Technology</span> – 
                <span class="city">São João da Boa Vista, Brazil </span>                
            </dd>
        </div> 
    </div>
    <h3>Work experience</h3>
    <div id="cvWorkExperience">
        <div class="work">
            <dt>2010-2011</dt>
            <dd>
                <span class="name">??????? </span> - 
                <span class="local">???????</span> – 
                <span class="city">???? </span> 
                <span class="details">?????</span>
            </dd>
        </div>
    </div>
    <h3>Languages</h3>
    <div id="cvLanguages">
        <div class="language">
            <dt>Portuguese</dt><dd>(mother tongue)</dd>
        </div>
        <div class="language">
            <dt>English</dt><dd>(Reading)</dd>
        </div>
    </div>
    <h3>Computer skills and competences</h3>
    <div id="cvCompExp">
        <div class="experience">
            <dt>Operation System:</dt><dd>&nbsp;</dd>
            <dt>Office:</dt><dd>&nbsp;</dd>
            <dt>Programming language:</dt><dd>&nbsp;</dd>
            
        </div>
    </div>

</div>

