<h2>Technology</h2>

<p></p>

<div id="listArticle" data-role="listview">
     <div class="article videogame"  >
          <img class="mini" src="<?php include 'videogame/article.php'; echo $article->picture; ?>" >           
          <div class="contents">
          <strong><a href="?u=videogame&p=technology"><?php echo $article->name; ?></a></strong>
          <div class="details">
             <?php
             echo $article->description ;
          ?>
          </div>
         
          
          
          </div>
     </div>
</div>

