<h2>Letter of presentation</h2>

<p>This is the page where you can view the presentation letter 
of the creators of this site. Click one to view.</p>

<div id="listLetter">
     <div class="pessoa">
        <a href="?u=bruna&p=letter">
          <div>Bruna Liberali</div>
        </a>
     </div>
     <div class="pessoa">
        <a href="?u=zanelli&p=letter">

          <div>Wellington Zanelli</div>
        </a>
     </div>
     <div class="pessoa">
        <a href="?u=tiago&p=letter">
          
          <div>Tiago Donizetti</div>
        </a>
     </div>
     
</div>

